apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: httpd-replicaset
  labels: 
    app: httpd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
      - name: ecomm
        image: httpd
        ports:
           - containerPort: 80

